export const DATABASE_CONSTANTS = {
  USER_DAO: "IUserDAO",
  ROLE_DAO: "IRoleDAO",
  TENANT_DAO: "ITenantDAO",
  PROJECT_DAO: "IProjectDAO",
  CLIENT_DAO: "IClientDAO",
  LOOKUP_DAO: "ILookupDAO",
  AUDIT_DAO: "IAUDITDAO",
  S3_DAO: "IS3DAO",
  RocAssetControl_DAO:"IROCDATA_DAO",
  ROC_DAO:"IROC_DAO",
  ROCControlFinding_DAO: "IROCCONTROLFINDING_DAO",
  ROC_DATA_PART_ONE_DAO: 'ROC_DATA_PART_ONE_DAO',
  APPENDIX_DAO: 'APPENDIX_DAO',

};
