# name: Build and Push Docker images

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     - name: Login to DockerHub
#       uses: docker/login-action@v3
#       with:
#         # username: ${{ secrets.DOCKERHUB_USERNAME }}
#         # password: ${{ secrets.DOCKERHUB_TOKEN }}
#         username: shivram70
#         password: "05078vihs&D"
#     - name: Build and push client
#       uses: docker/build-push-action@v5
#       with:
#         context: ./client
#         push: true
#         tags: shivram70/client-pi_audit:latest

#     - name: Build and push server
#       uses: docker/build-push-action@v5
#       with:
#         context: ./server
#         push: true
#         tags: shivram70/server-pi_audit:latest
